// <auto-generated />
using System;
using HotelReservation.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelReservation.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105043721_UpdateRoomTypeDescriptionsAndAddImageUrl")]
    partial class UpdateRoomTypeDescriptionsAndAddImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelReservation.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GuestId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("GuestId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("GuestId")
                        .HasColumnType("integer");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Confirmed");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxServiceCharge")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ReservationId");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations", t =>
                        {
                            t.HasCheckConstraint("chk_dates", "\"CheckOutDate\" > \"CheckInDate\"");
                        });
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Available");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            RoomNumber = "101",
                            RoomTypeId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = 2,
                            RoomNumber = "102",
                            RoomTypeId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = 3,
                            RoomNumber = "201",
                            RoomTypeId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = 4,
                            RoomNumber = "202",
                            RoomTypeId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = 5,
                            RoomNumber = "301",
                            RoomTypeId = 3,
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = 6,
                            RoomNumber = "302",
                            RoomTypeId = 3,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.RoomFeature", b =>
                {
                    b.Property<int>("RoomFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomFeatureId"));

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RoomFeatureId");

                    b.HasIndex("FeatureName")
                        .IsUnique();

                    b.ToTable("RoomFeatures");

                    b.HasData(
                        new
                        {
                            RoomFeatureId = 1,
                            FeatureName = "WiFi"
                        },
                        new
                        {
                            RoomFeatureId = 2,
                            FeatureName = "Air Conditioning"
                        },
                        new
                        {
                            RoomFeatureId = 3,
                            FeatureName = "Mini Bar"
                        },
                        new
                        {
                            RoomFeatureId = 4,
                            FeatureName = "Balcony"
                        },
                        new
                        {
                            RoomFeatureId = 5,
                            FeatureName = "Ocean View"
                        },
                        new
                        {
                            RoomFeatureId = 6,
                            FeatureName = "Jacuzzi"
                        });
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.RoomFeatureAssignment", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomFeatureId")
                        .HasColumnType("integer");

                    b.HasKey("RoomId", "RoomFeatureId");

                    b.HasIndex("RoomFeatureId");

                    b.ToTable("RoomFeatureAssignments");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            RoomFeatureId = 1
                        },
                        new
                        {
                            RoomId = 1,
                            RoomFeatureId = 2
                        },
                        new
                        {
                            RoomId = 2,
                            RoomFeatureId = 1
                        },
                        new
                        {
                            RoomId = 2,
                            RoomFeatureId = 2
                        },
                        new
                        {
                            RoomId = 3,
                            RoomFeatureId = 1
                        },
                        new
                        {
                            RoomId = 3,
                            RoomFeatureId = 2
                        },
                        new
                        {
                            RoomId = 3,
                            RoomFeatureId = 3
                        },
                        new
                        {
                            RoomId = 3,
                            RoomFeatureId = 4
                        },
                        new
                        {
                            RoomId = 4,
                            RoomFeatureId = 1
                        },
                        new
                        {
                            RoomId = 4,
                            RoomFeatureId = 2
                        },
                        new
                        {
                            RoomId = 4,
                            RoomFeatureId = 3
                        },
                        new
                        {
                            RoomId = 4,
                            RoomFeatureId = 4
                        },
                        new
                        {
                            RoomId = 5,
                            RoomFeatureId = 1
                        },
                        new
                        {
                            RoomId = 5,
                            RoomFeatureId = 2
                        },
                        new
                        {
                            RoomId = 5,
                            RoomFeatureId = 3
                        },
                        new
                        {
                            RoomId = 5,
                            RoomFeatureId = 4
                        },
                        new
                        {
                            RoomId = 5,
                            RoomFeatureId = 5
                        },
                        new
                        {
                            RoomId = 5,
                            RoomFeatureId = 6
                        },
                        new
                        {
                            RoomId = 6,
                            RoomFeatureId = 1
                        },
                        new
                        {
                            RoomId = 6,
                            RoomFeatureId = 2
                        },
                        new
                        {
                            RoomId = 6,
                            RoomFeatureId = 3
                        },
                        new
                        {
                            RoomId = 6,
                            RoomFeatureId = 4
                        },
                        new
                        {
                            RoomId = 6,
                            RoomFeatureId = 5
                        },
                        new
                        {
                            RoomId = 6,
                            RoomFeatureId = 6
                        });
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomTypeId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoomTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeId = 1,
                            BasePrice = 100.00m,
                            Capacity = 2,
                            Description = "A Standard Room offers comfort and convenience with essential amenities like a cozy bed, private bathroom, air conditioning, and Wi-Fi—ideal for both business and leisure stays.",
                            ImageUrl = "/images/standard-room.jpg",
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = 2,
                            BasePrice = 150.00m,
                            Capacity = 2,
                            Description = "A Deluxe Room offers extra space, stylish décor, and upgraded amenities for a more comfortable and luxurious stay.",
                            ImageUrl = "/images/delux-room.jpg",
                            TypeName = "Deluxe"
                        },
                        new
                        {
                            RoomTypeId = 3,
                            BasePrice = 300.00m,
                            Capacity = 4,
                            Description = "A Suite Room provides a separate living area, premium furnishings, and exclusive amenities for an indulgent experience.",
                            ImageUrl = "/images/suite-room.jpg",
                            TypeName = "Suite"
                        });
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.Guest", b =>
                {
                    b.HasOne("HotelReservation.Domain.Entities.AppUser", "User")
                        .WithOne("Guest")
                        .HasForeignKey("HotelReservation.Domain.Entities.Guest", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("HotelReservation.Domain.Entities.Guest", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelReservation.Domain.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.Room", b =>
                {
                    b.HasOne("HotelReservation.Domain.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.RoomFeatureAssignment", b =>
                {
                    b.HasOne("HotelReservation.Domain.Entities.RoomFeature", "RoomFeature")
                        .WithMany("RoomFeatureAssignments")
                        .HasForeignKey("RoomFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelReservation.Domain.Entities.Room", "Room")
                        .WithMany("RoomFeatureAssignments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("RoomFeature");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Guest");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.Guest", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.Room", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("RoomFeatureAssignments");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.RoomFeature", b =>
                {
                    b.Navigation("RoomFeatureAssignments");
                });

            modelBuilder.Entity("HotelReservation.Domain.Entities.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
